# Used when creating resources, used in more than one resource
variable "owner" {
  type        = string
  description = <<-EOT
    The name of the owner to tag resources with, usually your email address.
    Using your email address for this value allows teammates and other users 
     to contact you if a resource needs to be removed or has been around for a while.
  EOT
  default     = ""
}
variable "subnet_cidr" {
  type        = string
  description = <<-EOT
    The cidr of the private subnet you would like to create.
    This cidr must be within the IP bounds of the vpc_cidr.
  EOT
  default     = ""
}
variable "vpc_cidr" {
  type        = string
  description = <<-EOT
    This value sets the default private IP space for the created VPC.
    If the VPC creation is overridden then this module will not attempt to change the VPC's default subnet.
    VPCs generated with this module automatically give Amazon supplied public addresses to ec2 instances via an internet gateway.
    Access to the ec2 instances is then controlled by the security group.
    The security group generated by this module restricts access to servers to a single IP addess.
    The IP address assigned is the public address that ipinfo.io reports on the local system running this module.
  EOT
  default     = ""
}
# Specific to one resource generated
variable "vpc_name" {
  type        = string
  description = <<-EOT
    The name of the VPC to create.
    You can override the creation of a VPC by setting the "vpc_override" variable to true.
    This will then use the VPC with the given name, instead of creating it.
  EOT
}
variable "subnet_name" {
  type        = string
  description = <<-EOT
    The name of the subnet you would like to create.
    You must also set the cidr variable to the value you would like to use.
    You can override the creation of a subnet by setting the "subnet_override" variable to true.
    This will then use the subnet with the given name, instead of creating it.
    If you override the VPC creation, but not the subnet creation, 
      this module will attempt to associate the created subnet to the VPC.
    If the subnet is not available within the VPC's default CIDR, this module will fail.
    If you override the creation of the VPC and the creation of the subnet, 
      this module won't attempt to associate the subnet to the VPC.
  EOT
}
variable "security_group_name" {
  type        = string
  description = <<-EOT
    The name of the ec2 security group to create.
    You can override the creation of a security group by setting the "security_group_override" variable to true.
    This will then use the security group with the given name, instead of creating it.
  EOT
}
variable "ssh_key_name" {
  type        = string
  description = <<-EOT
    The name of the ec2 ssh key pair to create.
    You must also set the ssh_key variable to the public ssh key you would like to use.
    You can override the creation of an ssh key by setting the "ssh_key_override" variable to true.
    This will then use the ssh key with the given name, instead of creating it.
  EOT
}
variable "ssh_key" {
  type        = string
  description = <<-EOT
    The contents of the public ssh key object to create.
  EOT
  default     = ""
}

# Flow control
variable "vpc_override" {
  type        = bool
  description = <<-EOT
    Override the default behavior of generating a VPC, and use the VPC with the name given instead.
    Finding the vpc requires that it has a tag 'Name' matching the 'vpc_name' field.
  EOT
  default     = false
}
variable "subnet_override" {
  type        = bool
  description = <<-EOT
    Override the default behavior of generating a subnet, and use the subnet with the given name instead.
    Finding the subnet requires that it has a tag 'Name' matching the 'subnet_name' field.
  EOT
  default     = false
}
variable "security_group_override" {
  type        = bool
  description = <<-EOT
    Override the default behavior of generating an security group, and use the security group with the given name instead.
    Finding the security group requires that it has a tag 'Name' matching the 'security_group_name' field.
  EOT
  default     = false
}
variable "ssh_key_override" {
  type        = bool
  description = <<-EOT
    Override the default behavior of generating an ssh key, and use the ssh key with the given name instead.
    Finding the ssh key requires that it has a tag 'Name' matching the 'ssh_key_name' field.
  EOT
  default     = false
}
